"""Entity representing a pending limit order entry."""

from dataclasses import dataclass, field
from datetime import UTC, datetime

from discord_trade_bot.core.domain.value_objects.trading import TPDistributionRow, TradeSide


def _now_utc() -> datetime:
    return datetime.now(UTC)


@dataclass(slots=True, kw_only=True)
class PendingEntryEntity:
    """Represents a pending limit order that hasn't been filled yet.

    When a limit order is placed for entry, it's tracked here until filled.
    Once filled, it's converted to an ActivePositionEntity.

    Attributes:
        id: Unique identifier (generated by repository)
        symbol: Trading pair symbol
        source_id: Source identifier (e.g., Discord channel)
        message_id: Message ID from signal source
        exchange: Exchange name (binance, bybit, etc.)
        side: Trade side (LONG or SHORT)
        qty: Order quantity
        entry_price: Limit order price
        order_id: Exchange order ID
        stop_loss: Stop loss price (if SL/TP already attached)
        take_profits: Take profit prices (if SL/TP already attached)
        tp_distribution: TP distribution configuration
        status: Order status (pending, filled, cancelled, expired)
        created_at: When the order was created
        sl_tp_attached: Whether SL/TP orders are already placed
        sl_order_id: Stop loss order ID (if SL already placed)
        tp_order_ids: Take profit order IDs (if TPs already placed)
    """

    symbol: str
    source_id: str
    message_id: str
    exchange: str
    side: TradeSide
    qty: float
    entry_price: float
    order_id: str
    stop_loss: float | None = None
    take_profits: list[float] = field(default_factory=list)
    tp_distribution: list[TPDistributionRow] = field(default_factory=list)
    status: str = "pending"
    created_at: datetime = field(default_factory=_now_utc)
    sl_tp_attached: bool = False
    sl_order_id: str | None = None
    tp_order_ids: list[str] = field(default_factory=list)
    id: str | None = None
