general:
  mode: production
discord:
  watch_sources:
    - source_id: discord_source_1
      enabled: true
      channel_id: 1483388521925578785 # Replace with your Discord channel ID
      exchanges:
        - name: l
          position_size_pct: 40
        - name: mark
          position_size_pct: 10
      fixed_leverage: 5
      default_sl_percent: 3.2
      tp_distributions:
        3: # Для сигналов с 3 TP
          - label: tp1
            close_pct: 50
          - label: tp2
            close_pct: 30
          - label: tp3
            close_pct: 20
        4: # Для сигналов с 4 TP
          - label: tp1
            close_pct: 40
          - label: tp2
            close_pct: 30
          - label: tp3
            close_pct: 20
          - label: tp4
            close_pct: 10
        5: # Для сигналов с 5 TP
          - label: tp1
            close_pct: 30
          - label: tp2
            close_pct: 25
          - label: tp3
            close_pct: 20
          - label: tp4
            close_pct: 15
          - label: tp5
            close_pct: 10
exchanges:
  binance:
    timeout_seconds: 15
  bybit:
    demo: true
    timeout_seconds: 15
fees:
  maker: 0.0002
  taker: 0.00055
  break_even_fee_mode: taker
  break_even_extra_buffer: 0.0
telegram:
  enabled: false
  chat_id: 1234567890 # Replace with your Telegram chat ID
state:
  file: agent_state.db
  trades_file: agent_trades.jsonl
